# Generated by Django 3.2.7 on 2022-05-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0002_auto_20220515_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
