# Generated by Django 3.2.15 on 2023-02-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0007_alter_post_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_images',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
